# Generated by Django 5.0.7 on 2024-08-19 19:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobrole', models.TextField()),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('location', models.TextField()),
                ('experience', models.TextField()),
                ('resume', models.FileField(upload_to='resumes')),
            ],
        ),
        migrations.CreateModel(
            name='Joblisting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.TextField()),
                ('jobimage', models.ImageField(upload_to='joblisting_images')),
                ('jobdescription', ckeditor.fields.RichTextField()),
                ('openpositions', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Blog',
            new_name='Blogpost',
        ),
    ]
