# Generated by Django 5.0.7 on 2024-08-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_applicant_joblisting_rename_blog_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='department',
            field=models.TextField(default='Management'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='location',
            field=models.TextField(default='Noida'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='reports_to',
            field=models.TextField(default=''),
        ),
    ]
